version: "3"

networks:
  front-tier:
  back-tier:
    driver: bridge

services:
  reverse-proxy:
    image: nginx:stable
    restart: unless-stopped
    command: "/bin/sh -c 'while :; do sleep 6h & wait $${!}; nginx -s reload; done & nginx -g \"daemon off;\"'"
    depends_on:
      - app
      - db
    volumes:
      - ./data/nginx:/etc/nginx/conf.d
      - ./data/certbot/conf:/etc/letsencrypt
      - ./data/certbot/www:/var/www/certbot
    ports:
      - "80:80"
      - "443:443"
    networks:
      - front-tier
      - back-tier
  app:
    image: ownyourday:latest
    restart: unless-stopped
    expose:
      - "3000"
    depends_on:
      - db
    volumes:
      - ./log:/app/log
    networks:
      - front-tier
      - back-tier
  db:
    image: postgres:11
    restart: unless-stopped
    expose:
      - "5432"
    env_file:
      - db.env
    volumes:
      - ./tmp/db:/var/lib/postgresql/data
    networks:
      - back-tier
  certbot:
    image: certbot/certbot
    restart: unless-stopped
    entrypoint: "/bin/sh -c 'trap exit TERM; while :; do certbot renew; sleep 12h & wait $${!}; done;'"
    volumes:
      - ./data/certbot/conf:/etc/letsencrypt
      - ./data/certbot/www:/var/www/certbot
    networks:
      - back-tier